### ISSUE TITLE
Cant read the results

### ISSUE THREAD

**Issue by priyankaiit** [sjpfenninger/uk-calliope#1]
I have tried to run the run_planning.yaml file and the solution.nc file has got created in the output folder. I have run calliope from the command prompt. I have tried to read the results using this calliope.read.read_netcdf('solution.nc') but it seems not to be working. Kindly suggest how to read the solution.nc file

**Comment by sjpfenninger** [comment]
@priyankaiit apologies for the much delayed response, it looks like I wasn't getting notifications for issues in this repository. If this is still a problem, given that it sounds like an issue with Calliope itself rather than this specific model, can you open an issue with more details on the error you are getting on the main [Calliope repository](https://github.com/calliope-project/calliope) or join us on our [Gitter chat](https://gitter.im/calliope-project/calliope)? I'm closing this issue here.
